const trustPolicy = {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "SecAudit",
        "Effect": "Allow",
        "Action": [
          "cloudfront:List*",
          "cloudfront:Get*",
          "cloudfront:Describe*",
          "ecr:DescribeRepositories",
          "ecr:BatchGetRepositoryScanningConfiguration",
          "iam:List*",
          "iam:Get*",
          "lambda:GetFunctionConfiguration",
          "lambda:GetFunctionUrlConfig",
          "cloudwatch:GetMetricStatistics",
          "ec2:DescribeInstances",
          "ec2:DescribeVpcs",
          "ec2:DescribeSecurityGroups",
          "ec2:DescribeNetworkInterfaces",
          "redshift:DescribeClusters",
          "inspector2:BatchGetAccountStatus",
          "ec2:DescribeFlowLogs",
          "securityhub:GetEnabledStandards",
          "s3:ListAllMyBuckets",
          "s3:GetBucketLogging",
          "s3:GetEncryptionConfiguration",
          "s3:GetBucketPolicyStatus",
          "s3:GetBucketAcl",
          "s3:GetBucketVersioning",
          "s3:GetAccountPublicAccessBlock",
          "s3:GetBucketCORS",
          "s3:GetBucketPolicy",
          "s3:GetBucketVersioning",
          "s3:GetEncryptionConfiguration",
          "s3:GetLifecycleConfiguration",
          "sts:GetCallerIdentity",
          "wafv2:List*",
          "wafv2:Get*"
        ],
        "Resource": "*"
      },
      {
        "Sid": "SecAuditServiceQuotas",
        "Effect": "Allow",
        "Action": [
          "states:ListStateMachines",
          "servicequotas:GetServiceQuota",
          "acm:List*",
          "acm:DescribeCertificate",
          "athena:ListWorkGroups",
          "athena:GetWorkGroup",
          "apigateway:GET",
          "autoscaling:Describe*",
          "cloudformation:DescribeAccountLimits",
          "cloudformation:DescribeStacks",
          "cloudwatch:GetMetricData",
          "ds:GetDirectoryLimits",
          "ec2:Describe*",
          "ec2:GetEbsDefaultKmsKeyId",
          "ec2:GetEbsEncryptionByDefault",
          "ecs:Describe*",
          "ecs:List*",
          "eks:Describe*",
          "eks:List*",
          "elasticache:DescribeCacheClusters",
          "elasticache:DescribeCacheParameterGroups",
          "elasticache:DescribeCacheSecurityGroups",
          "elasticache:DescribeCacheSubnetGroups",
          "elasticbeanstalk:DescribeApplicationVersions",
          "elasticbeanstalk:DescribeApplications",
          "elasticbeanstalk:DescribeEnvironments",
          "elasticfilesystem:DescribeFileSystems",
          "firehose:ListDeliveryStreams",
          "lambda:GetAccountSettings",
          "redshift:DescribeClusterSnapshots",
          "redshift:DescribeClusterSubnetGroups",
          "route53:GetHostedZone",
          "route53:GetHostedZoneLimit",
          "route53:ListHostedZones",
          "servicequotas:List*",
          "servicequotas:Get*",
          "ses:Get*",
          "ses:List*",
          "support:Describe*",
          "support:SearchForCases",
          "trustedadvisor:Describe*",
          "trustedadvisor:GenerateReport",
          "trustedadvisor:RefreshCheck",
          "iam:GenerateCredentialReport",
          "iam:GetCredentialReport",
          "secretsmanager:ListSecrets",
          "secretsmanager:DescribeSecret",
          "sns:List*",
          "sns:Get*",
          "artifact:ListReports",
          "artifact:GetReportMetadata",
          "artifact:GetReport",
          "artifact:GetTermForReport"
        ],
        "Resource": "*"
      },
      {
        "Sid": "NewReadAccountBillingPermissions",
        "Effect": "Allow",
        "Action": [
          "consolidatedbilling:GetAccountBillingRole",
          "consolidatedbilling:ListLinkedAccounts",
          "billing:Get*",
          "payments:ListPaymentPreferences",
          "invoicing:GetInvoicePDF",
          "invoicing:ListInvoiceSummaries"
        ],
        "Resource": "*"
      }
    ]
  }

export default trustPolicy;